In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

In [3]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
my_list = [1, "hi"]
my_list

[1, 'hi']

In [6]:
my_array = np.array((1, "hi"))
my_array

array(['1', 'hi'], dtype='<U21')

In [7]:
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [8]:
list_2d = [[1, 2], [3, 4], [5, 6]]
list_2d

[[1, 2], [3, 4], [5, 6]]

In [9]:
array_2d = np.array(list_2d)
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.arange(1, 5)  # from 1 inclusive to 5 exclusive

array([1, 2, 3, 4])

In [11]:
np.arange(0, 11, 2)  # step by 2 from 1 to 11

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.linspace(0, 10, 5)  # 5 equally spaced points between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.ones((2, 2))  # an array of ones with size 2 x 2

array([[1., 1.],
       [1., 1.]])

In [14]:
np.zeros((2, 3))  # an array of zeros with size 2 x 3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.full((3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [16]:
np.full((3, 3, 3), 3.14)  # an array of the number 3.14 with size 3 x 3 x 3

array([[[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14]]])

In [17]:
np.random.rand(5, 2)  # random numbers uniformly distributed from 0 to 1 with size 5 x 2

array([[0.18266272, 0.50532538],
       [0.93870519, 0.53992208],
       [0.77110881, 0.83831398],
       [0.36031304, 0.47116661],
       [0.68636192, 0.58625289]])

In [18]:
print(dir(np.ndarray))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [19]:
x = np.random.rand(5, 2)
x

array([[0.56523817, 0.07604944],
       [0.74730656, 0.91192971],
       [0.32530342, 0.02843309],
       [0.66361726, 0.28894384],
       [0.82302095, 0.35079451]])

In [20]:
x.transpose()

array([[0.56523817, 0.74730656, 0.32530342, 0.66361726, 0.82302095],
       [0.07604944, 0.91192971, 0.02843309, 0.28894384, 0.35079451]])

In [21]:
x.mean()

0.4780636957318718

In [22]:
x.astype(int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [23]:
array_1d = np.ones(3)
print(f"Dimensions: {array_1d.ndim}")
print(f"     Shape: {array_1d.shape}")
print(f"      Size: {array_1d.size}")

Dimensions: 1
     Shape: (3,)
      Size: 3


In [24]:
def print_array(x):
    print(f"Dimensions: {x.ndim}")
    print(f"     Shape: {x.shape}")
    print(f"      Size: {x.size}")
    print("")
    print(x)

In [25]:
array_2d = np.ones((3, 2))
print_array(array_2d)

Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [26]:
array_4d = np.ones((1, 2, 3, 4))
print_array(array_4d)

Dimensions: 4
     Shape: (1, 2, 3, 4)
      Size: 24

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [27]:
x = np.ones(5)
print_array(x)

Dimensions: 1
     Shape: (5,)
      Size: 5

[1. 1. 1. 1. 1.]


In [28]:
y = np.ones((1, 5))
print_array(y)

Dimensions: 2
     Shape: (1, 5)
      Size: 5

[[1. 1. 1. 1. 1.]]


In [29]:
z = np.ones((5, 1))
print_array(z)

Dimensions: 2
     Shape: (5, 1)
      Size: 5

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [30]:
np.array_equal(x, x)

True

In [31]:
np.array_equal(x, y)

False

In [32]:
np.array_equal(x, z)

False

In [33]:
np.array_equal(y, z)

False

In [34]:
print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")

x: [1. 1. 1. 1. 1.]
y: [[1. 1. 1. 1. 1.]]
z: [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [35]:
x + y  # makes sense

array([[2., 2., 2., 2., 2.]])

In [36]:
y + z  # wait, what?

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [37]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [38]:
y = x + 1
y

array([2., 2., 2., 2.])

In [39]:
x - y

array([-1., -1., -1., -1.])

In [40]:
x == y

array([False, False, False, False])

In [41]:
x * y

array([2., 2., 2., 2.])

In [42]:
x ** y

array([1., 1., 1., 1.])

In [43]:
x / y

array([0.5, 0.5, 0.5, 0.5])

In [44]:
np.array_equal(x, y)

False

In [45]:
a = np.ones((2, 2))
b = np.ones((3, 3))
a + b

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [46]:
cost = np.array([20, 15, 25])
print("Pie cost:")
print(cost)
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print("\nPie sales (#):")
print(sales)

Pie cost:
[20 15 25]

Pie sales (#):
[[2 3 1]
 [6 3 3]
 [5 3 5]]


In [47]:
total = np.zeros((3, 3))  # initialize an array of 0's
for col in range(sales.shape[1]):
    total[:, col] = sales[:, col] * cost
total

array([[ 40.,  60.,  20.],
       [ 90.,  45.,  45.],
       [125.,  75., 125.]])

In [48]:
cost = np.repeat(cost, 3).reshape((3, 3))
cost

array([[20, 20, 20],
       [15, 15, 15],
       [25, 25, 25]])

In [49]:
cost * sales

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

In [50]:
cost = np.array([20, 15, 25]).reshape(3, 1)
print(f" cost shape: {cost.shape}")
sales = np.array([[2, 3, 1], [6, 3, 3], [5, 3, 5]])
print(f"sales shape: {sales.shape}")

 cost shape: (3, 1)
sales shape: (3, 3)


In [51]:
sales * cost

array([[ 40,  60,  20],
       [ 90,  45,  45],
       [125,  75, 125]])

In [52]:
cost = np.array([20, 15, 25]).reshape(3, 1)
sales = np.array([[2, 3, 1],
                  [6, 3, 3],
                  [5, 3, 5]])
total = np.zeros((3, 3))

time_loop = %timeit -q -o -r 3 for col in range(sales.shape[1]): total[:, col] = sales[:, col] * np.squeeze(cost)
time_vec = %timeit -q -o -r 3 cost * sales
print(f"Broadcasting is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Broadcasting is 4.46x faster than looping here.


In [53]:
a = np.ones((3, 2))
b = np.ones((3, 2, 1))
print(f"The shape of a is: {a.shape}")
print(f"The shape of b is: {b.shape}")
print("")
try:
    print(f"The shape of a + b is: {(a + b).shape}")
except:
    print(f"ERROR: arrays are NOT broadcast compatible!")

The shape of a is: (3, 2)
The shape of b is: (3, 2, 1)

ERROR: arrays are NOT broadcast compatible!


In [54]:
x = np.full((4, 3), 3.14)
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [55]:
x.reshape(6, 2)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [56]:
x.reshape(2, -1)  # using -1 will calculate the dimension for you (if possible)

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [57]:
a = np.ones(3)
print_array(a)
b = np.ones((3, 2))
print_array(b)

Dimensions: 1
     Shape: (3,)
      Size: 3

[1. 1. 1.]
Dimensions: 2
     Shape: (3, 2)
      Size: 6

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [58]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [59]:
print_array(a[:, np.newaxis])  # same as a[:, None]

Dimensions: 2
     Shape: (3, 1)
      Size: 3

[[1.]
 [1.]
 [1.]]


In [60]:
a[:, np.newaxis] + b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [61]:
x

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [62]:
print_array(x.flatten())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [63]:
print_array(x.ravel())

Dimensions: 1
     Shape: (12,)
      Size: 12

[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]


In [64]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x[3]

3

In [66]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
x[:4]

array([0, 1, 2, 3])

In [68]:
x[2:5]

array([2, 3, 4])

In [69]:
x[2:3]

array([2])

In [70]:
x[-1]

9

In [71]:
x[-2]

8

In [72]:
x[5:0:-1]

array([5, 4, 3, 2, 1])

In [73]:
x = np.random.randint(10, size=(4, 6))
x

array([[5, 8, 9, 9, 5, 9],
       [5, 1, 2, 8, 5, 3],
       [6, 3, 9, 6, 6, 7],
       [8, 2, 5, 9, 8, 4]])

In [74]:
x[3, 4]  # do this

8

In [75]:
x[3][4]  # i do not like this as much

8

In [76]:
x[3]

array([8, 2, 5, 9, 8, 4])

In [77]:
len(x)  # generally, just confusing

4

In [78]:
x.shape

(4, 6)

In [79]:
x[:, 2]  # column number 2

array([9, 2, 9, 5])

In [80]:
x[2:, :3]

array([[6, 3, 9],
       [8, 2, 5]])

In [81]:
x.T

array([[5, 5, 6, 8],
       [8, 1, 3, 2],
       [9, 2, 9, 5],
       [9, 8, 6, 9],
       [5, 5, 6, 8],
       [9, 3, 7, 4]])

In [82]:
x

array([[5, 8, 9, 9, 5, 9],
       [5, 1, 2, 8, 5, 3],
       [6, 3, 9, 6, 6, 7],
       [8, 2, 5, 9, 8, 4]])

In [83]:
x[1, 1] = 555555
x

array([[     5,      8,      9,      9,      5,      9],
       [     5, 555555,      2,      8,      5,      3],
       [     6,      3,      9,      6,      6,      7],
       [     8,      2,      5,      9,      8,      4]])

In [84]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [85]:
z[0] = 5
z

array([5., 0., 0., 0., 0.])

In [86]:
x = np.random.rand(10)
x

array([0.73751045, 0.03482754, 0.53380521, 0.3241315 , 0.48742132,
       0.49429716, 0.7816131 , 0.56695028, 0.75976745, 0.24751463])

In [87]:
x + 1

array([1.73751045, 1.03482754, 1.53380521, 1.3241315 , 1.48742132,
       1.49429716, 1.7816131 , 1.56695028, 1.75976745, 1.24751463])

In [88]:
x_thresh = x > 0.5
x_thresh

array([ True, False,  True, False, False, False,  True,  True,  True,
       False])

In [89]:
x[x_thresh] = 0.5  # set all elements  > 0.5 to be equal to 0.5
x

array([0.5       , 0.03482754, 0.5       , 0.3241315 , 0.48742132,
       0.49429716, 0.5       , 0.5       , 0.5       , 0.24751463])

In [90]:
x = np.random.rand(10)
x

array([0.49988976, 0.6706792 , 0.38164568, 0.06454246, 0.29134232,
       0.42082875, 0.402567  , 0.25200321, 0.94061053, 0.08461321])

In [91]:
x[x > 0.5] = 0.5
x

array([0.49988976, 0.5       , 0.38164568, 0.06454246, 0.29134232,
       0.42082875, 0.402567  , 0.25200321, 0.5       , 0.08461321])

In [92]:
sides = np.array([3, 4])

In [93]:
np.sqrt(np.sum([np.power(sides[0], 2), np.power(sides[1], 2)]))

5.0

In [94]:
(sides ** 2).sum() ** 0.5

5.0

In [95]:
np.linalg.norm(sides)  # you'll learn more about norms in 573

5.0

In [96]:
np.hypot(*sides)

5.0

In [97]:
# DONT DO THIS
array = np.array(range(5))
for i, element in enumerate(array):
    array[i] = element ** 2
array

array([ 0,  1,  4,  9, 16])

In [98]:
# DO THIS
array = np.array(range(5))
array **= 2 

In [99]:
# loop method
array = np.array(range(5))
time_loop = %timeit -q -o -r 3 for i, element in enumerate(array): array[i] = element ** 2
# vectorized method
array = np.array(range(5))
time_vec = %timeit -q -o -r 3 array ** 2
print(f"Vectorized operation is {time_loop.average / time_vec.average:.2f}x faster than looping here.")

Vectorized operation is 3.49x faster than looping here.
