In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
print(f"The shape of this ndarray is: {a.shape}")
print(f" The number of dimensions is: {a.ndim}")
print(f"   The number of elements is: {a.size}")

The shape of this ndarray is: (6,)
 The number of dimensions is: 1
   The number of elements is: 6


In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(f"The shape of this ndarray is: {a.shape}")
print(f" The number of dimensions is: {a.ndim}")
print(f"   The number of elements is: {a.size}")

The shape of this ndarray is: (2, 3)
 The number of dimensions is: 2
   The number of elements is: 6


In [6]:
a = np.arange(36).reshape(2, 3, 3, 2)
a

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [7]:
print(f"The shape of this ndarray is: {a.shape}")
print(f" The number of dimensions is: {a.ndim}")
print(f"   The number of elements is: {a.size}")

The shape of this ndarray is: (2, 3, 3, 2)
 The number of dimensions is: 4
   The number of elements is: 36


In [8]:
a = np.array([1, 2, 3, 4, 5, 6], dtype='int8')
a

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [9]:
a.itemsize

1

In [10]:
np.array([126, 127, 128, 129, 130, 131, 132], dtype='int8')

/tmp/ipykernel_16840/2454158965.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([126, 127, 128, 129, 130, 131, 132], dtype='int8')
/tmp/ipykernel_16840/2454158965.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([126, 127, 128, 129, 130, 131, 132], dtype='int8')
/tmp/ipykernel_16840/2454158965.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 130 to int8 will fail in the future.
For the old behavior, usually:
    np.arr

array([ 126,  127, -128, -127, -126, -125, -124], dtype=int8)

In [11]:
np.array([126, 127, 128, 129, 130, 131, 132], dtype='int16')

array([126, 127, 128, 129, 130, 131, 132], dtype=int16)

In [12]:
a = np.array([['a', 'b', 'c'], 1, 3.14159], dtype='object')
a

array([list(['a', 'b', 'c']), 1, 3.14159], dtype=object)

In [13]:
list(map(type, a))

[list, int, float]

In [14]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype='int16')
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)

In [15]:
a.strides

(4, 2)

In [16]:
a.strides = (2, 4)
a

array([[1, 3],
       [2, 4],
       [3, 5]], dtype=int16)

In [17]:
a = a.flatten()
a

array([1, 3, 2, 4, 3, 5], dtype=int16)

In [18]:
a.strides

(2,)

In [19]:
a = np.arange(18, dtype='int8').reshape(3, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]], dtype=int8)

In [20]:
a.strides

(6, 2, 1)

In [21]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype='int8')
a

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int8)

In [22]:
a.strides

(2, 1)

In [23]:
a.flatten()

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [24]:
a.shape = (2, 3)
a.strides = (3, 1)
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [25]:
a = np.arange(18, dtype='int8')
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17], dtype=int8)

In [26]:
a = a.reshape(3, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]], dtype=int8)

In [27]:
a.strides

(6, 2, 1)

In [28]:
a = np.arange(18, dtype='int8').reshape(3, 3, 2, order="C")
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]], dtype=int8)

In [29]:
a = np.arange(18, dtype='int8').reshape(3, 3, 2, order="F")
a

array([[[ 0,  9],
        [ 3, 12],
        [ 6, 15]],

       [[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]]], dtype=int8)

In [30]:
import time
import matplotlib.pyplot as plt
from numpy.lib.stride_tricks import as_strided
plt.style.use('ggplot')
plt.rcParams.update({'font.size': 16, 'figure.figsize': (8,6), 'axes.grid': False})

In [31]:
image = plt.imread('img/chapter6/tomas_beuzen.png')[:,:,0]
plt.imshow(image, cmap='gray');

In [32]:
f = np.array([[-2, -1, 0],
              [-1, 1, 1],
              [0, 1, 2]])

In [33]:
start = time.time()    # start time
size = f.shape[0]      # filter size
win_img = as_strided(  # Now use as_strided to get a windowed view of the array
    image,             # image to view as windows
    shape=(image.shape[0] - size + 1, image.shape[1] - size + 1, size, size),  # the shape of the new view (398, 398, 3, 3), the edge pixels are cut-off, but we could always pad if we wanted to here
    strides=image.strides * 2,  # this just duplicates the strides as we are now working in 4 dimensions, strides will be (6400, 16, 6400, 16)
)
filtered_image = (win_img * f).sum(axis=(2, 3))  # apply filter to each window (the 3rd and 4th dimensions of win_img)
plt.imshow(filtered_image, cmap="gray")
print(f"Wall time taken for convolution: {time.time()-start:.4f}s")

Wall time taken for convolution: 0.0277s
